package livephoto.core.jpeg

import livephoto.core.*
import livephoto.core.binary.*
import livephoto.core.exif.ExifMarkerPatch
import livephoto.core.apple.AppleImagePatch

internal data class JpegPatch(val range: ByteRange, val replacement: Bytes, val exifProof: ExifMarkerPatch? = null, val appleProof: AppleImagePatch? = null)
internal data class JpegRewritePlan(val patches: List<JpegPatch>, val outputLength: ULong)

internal object JpegRewrite {
    fun appSegment(marker: Int, payload: Bytes): CoreResult<Bytes> = attemptNow {
        if (marker !in 0xe0..0xef) fail("INVALID_ARGUMENT", "Only APP markers can be generated by this helper")
        if (payload.size > 65_533) fail("VALUE_NOT_REPRESENTABLE", "APP payload does not fit a JPEG segment")
        val output = ByteArray(payload.size + 4)
        output[0] = 0xff.toByte()
        output[1] = marker.toByte()
        unsignedBytes((payload.size + 2).toULong(), 2, Endian.Big).copyInto(output, 2)
        payload.copyInto(output, 4)
        Bytes(output)
    }

    /** Only complete APP replacement/removal or APP insertion before the first scan is permitted. */
    fun plan(structure: JpegStructure, patches: List<JpegPatch>): CoreResult<JpegRewritePlan> = attemptNow {
        val ordered = patches.sortedBy { it.range.offset }
        var previousEnd = 0uL
        var outputLength = structure.primary.length
        val firstScanHeader = structure.segments.firstOrNull { it.marker == 0xda }?.range?.offset ?: structure.primary.endExclusive - 2uL
        for (patch in ordered) {
            if (!patch.range.fitsWithin(structure.primary.length) || patch.range.offset < 2uL || patch.range.offset < previousEnd) {
                fail("INVALID_ARGUMENT", "JPEG patches overlap or exceed the image carrier")
            }
            val segment = structure.segments.firstOrNull { it.range == patch.range && it.marker in 0xe0..0xef }
            val insertion = patch.range.length == 0uL && patch.range.offset <= firstScanHeader &&
                structure.segments.any { it.range.offset == patch.range.offset || it.range.endExclusive == patch.range.offset }
            if (segment == null && !insertion) fail("UNSAFE_METADATA_REWRITE", "Patch is not a complete APP segment or a safe APP boundary")
            validateAppBytes(patch.replacement)
            val proof = patch.exifProof
            val apple = patch.appleProof
            if (apple != null && (proof != null || structure.hasMpf || structure.hasExtendedXmp ||
                    patch.replacement != appSegment(0xe1, apple.payload).orThrow() ||
                    apple.originalTiffRange == null && (!insertion || structure.hasExif) ||
                    apple.originalTiffRange != null && (segment?.payloadKind != AppPayloadKind.Exif || segment.payload == null ||
                        apple.originalTiffRange != ByteRange(segment.payload.offset + 6uL, segment.payload.length - 6uL))))
                fail("UNSAFE_METADATA_REWRITE", "Apple EXIF authorization does not match this exact APP segment", Stage.Plan)
            if (proof != null) {
                val expected = appSegment(0xe1, proof.replacementPayload).orThrow()
                if (patch.replacement != expected || proof.originalTiffRange == null && (!insertion || structure.hasExif) ||
                    proof.originalTiffRange != null && (segment?.payloadKind != AppPayloadKind.Exif || segment.payload == null ||
                        proof.originalTiffRange != ByteRange(segment.payload.offset + 6uL, segment.payload.length - 6uL))) fail("UNSAFE_METADATA_REWRITE", "EXIF authorization does not match this exact JPEG patch")
            }
            if (segment?.payloadKind == AppPayloadKind.Mpf || proof == null && apple == null && (segment?.payloadKind == AppPayloadKind.Exif || protectedReplacement(patch.replacement))) {
                fail("UNSAFE_METADATA_REWRITE", "MPF and EXIF edits require a verified parsed dependency model")
            }
            if (structure.hasExtendedXmp && (segment?.payloadKind == AppPayloadKind.Xmp || segment?.payloadKind == AppPayloadKind.ExtendedXmp || insertion)) {
                fail("UNSAFE_METADATA_REWRITE", "Extended XMP must be fully reassembled before rewriting")
            }
            outputLength -= patch.range.length
            outputLength = checkedAdd(outputLength, patch.replacement.size.toULong())
            previousEnd = patch.range.endExclusive
        }
        if (structure.hasMpf && ordered.any { it.replacement.size.toULong() != it.range.length }) {
            fail("GAINMAP_PRESERVATION_UNAVAILABLE", "MPF dependencies need verified relocation before resizing metadata")
        }
        // Unknown EXIF/MakerNote relocation is blocked until the caller has a parsed safe model.
        for (patch in ordered) {
            if (patch.replacement.size.toULong() != patch.range.length && structure.segments.any { exif ->
                    exif.payloadKind == AppPayloadKind.Exif && exif.range.offset >= patch.range.endExclusive &&
                        ordered.none { it.range == exif.range && it.exifProof?.isNoOp == false }
                }) {
                fail("UNSAFE_METADATA_REWRITE", "Metadata resizing would relocate an unverified EXIF block")
            }
        }
        JpegRewritePlan(frozenList(ordered), outputLength)
    }

    suspend fun write(reader: BinaryReader, writer: BinaryWriter, structure: JpegStructure, plan: JpegRewritePlan, context: Context): CoreResult<Unit> = attempt {
        val verifiedPlan = JpegRewrite.plan(structure, plan.patches).orThrow()
        if (verifiedPlan.outputLength != plan.outputLength) fail("INVALID_ARGUMENT", "JPEG rewrite plan length is inconsistent")
        var position = 0uL
        for (patch in verifiedPlan.patches) {
            patch.appleProof?.let { proof ->
                if (reader.identity().orThrow() != proof.sourceIdentity || proof.originalTiffRange != null &&
                    sha256Range(reader, proof.originalTiffRange).orThrow() != proof.originalTiffDigest)
                    fail("SOURCE_CHANGED", "Apple EXIF authorization no longer matches input", Stage.WriteProtocol)
            }
            patch.exifProof?.let { proof ->
                if (reader.identity().orThrow() != proof.sourceIdentity || proof.originalTiffRange != null &&
                    sha256Range(reader, proof.originalTiffRange).orThrow() != proof.originalTiffDigest) fail("SOURCE_CHANGED", "Verified EXIF source changed before staging write")
            }
            copyRange(reader, writer, ByteRange(position, patch.range.offset - position), context).orThrow()
            writer.writeAll(patch.replacement).orThrow()
            position = patch.range.endExclusive
        }
        copyRange(reader, writer, ByteRange(position, structure.primary.endExclusive - position), context).orThrow()
    }

    private fun validateAppBytes(bytes: Bytes): Unit {
        if (bytes.size == 0) return
        if (bytes.size < 4 || (bytes[0].toInt() and 0xff) != 0xff || (bytes[1].toInt() and 0xff) !in 0xe0..0xef) {
            fail("INVALID_ARGUMENT", "A replacement must contain exactly one APP segment")
        }
        if (readUnsigned(bytes.slice(2, 4), Endian.Big) + 2uL != bytes.size.toULong()) fail("INVALID_ARGUMENT", "Replacement APP length is inconsistent")
    }

    private fun protectedReplacement(bytes: Bytes): Boolean {
        if (bytes.size < 4) return false
        val marker = bytes[1].toInt() and 0xff
        val prefix = if (marker == 0xe1) "Exif\u0000\u0000" else if (marker == 0xe2) "MPF\u0000" else return false
        return bytes.size >= 4 + prefix.length && prefix.indices.all { (bytes[it + 4].toInt() and 0xff) == prefix[it].code }
    }
}
